### PR TITLE
Just updated with some problems I had with the tutorial

### PR DESCRIPTION
**Pull request by vongohren**
Thanks for the write up btw, learned alot

### CODE REVIEW

**Comment by mshearer0** [comment]
Great tutorial and helpful pull request. 

Few typos/updates/suggestions to get things running:

1.  Deploy command should be --trigger-http and --runtime=nodejs14  (or swap 14 for more recent version). When deploying need to agree to unauthorised access to the function.

2. The property with ac-enabled should have client-id as sample-ac-client (not a repeat of sample-ropc-client) and have the client-secret property set

3. The sample-acpkce-client has https://www.google.com as its client-secret value instead of sample-client-secret. 

4. The POST commands should have the url in double quotes (at least for windows)

5. PKCE example: Verifier is mis-spelt as verfier.

6. Resource Owner example: username=sample-user not sample-username.

7. PUG file needs updating with GCP region and project values before deployment.

8. To generate pem key files you can use openssl on command line as:

openssl genrsa -aes256 -out priv.pem 4096
openssl rsa -in priv.pem -pubout > public.pem
openssl rsa -in priv.pem -out private.pem

Last step is needed to remove passphrase which will cause tutorial to fail.

**Comment by vongohren** [comment]
Thanks for feedback and if it was more fitting when it was provided, Id love to take it on, unfortunately this is so old that I have no recollection of what it really is. So I would choose to close it. But if this is something you want to update and merge, sure thing.

As the owner Il let you decide

**Comment by mshearer0** [comment]
I’ve commented on the medium article as well, if anyone else picks this up and wants to follow it.

**Comment by vongohren** [comment]
Closing this as it populates my list of pullrequests

**Pull request closed without merging**
